# Some of these need to be formatted in python to replace {} with study ID
in_study_meta: 'gs://genetics-portal-dev-raw/eqtl_catalogue/210824/tabix_ftp_paths.tsv'
in_nominal: 'gs://genetics-portal-dev-raw/eqtl_catalogue/210824/sumstats_dedup/{}'
in_gene_meta: 'gs://genetics-portal-dev-raw/eqtl_catalogue/210824/*_phenotype_metadata.tsv.gz'
in_biofeatures_map: 'gs://genetics-portal-data/lut/biofeature_lut_190920.w_composites.json'
out_parquet: 'gs://genetics-portal-dev-sumstats/unfiltered/molecular_trait/'
